version: "3"

networks:
  bsnet:

services:
  jenkins-ui:
    image: jenkins/jenkins-bs
    build: .
    volumes:
     - "/var/jenkins_home:/var/jenkins_home"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - ${dockerpath}:/usr/bin/docker
    ports:
     - "8080:8080"
#     - "50000:50000"
    restart: always
    privileged: true
    user: root
    networks:
     - voteapp
    deploy:
     replicas: 1
     placement:
      constraints: [node.role == manager]
     resources:
      limits:
       cpus: '0.5'
#       memory: 400M
    networks:
      - bsnet
    environment:
      - LOGSPOUT=ignore