version: "3"

networks:
  bsnet:

volumes:
  rabbit_mq: {}

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "15672:15672"
    restart: always
    networks:
     - voteapp
    volumes:
     - rabbit_mq:/var/lib/rabbitmq:rw
    deploy:
     replicas: 1
     placement:
        constraints:
          - node.role == ${NODEROLE}
     resources:
      limits:
       cpus: '0.5'
       memory: 400M
    networks:
      - bsnet
    environment:
      - RABBITMQ_DEFAULT_USER= ${RABBITMQUSER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQPASS}