pipeline {
    agent { label 'master' }
    parameters {
        choice(choices: ['Staging', 'Production'], description: 'Staging or Production environment?', name: 'buildenvironment')
    }
    stages { 
      
        stage('Deploy to Staging') {  
            environment {
                NODEROLE = "manager"
                RABBITMQUSER = "rabbit_staging"
                RABBITMQPASS= "rabbitpasswrd"
            }
            when {
                // Only say hello if a "greeting" is requested
                expression { params.buildenvironment == 'Staging' }
             }  
            steps {  
                echo 'Deploy Rabbit to staging'
                sh "docker stack deploy --compose-file infrastructure/RabbitMQ/docker-compose.yml bsapp"
            }
        }
        
        stage('Deploy to Production') {  
            environment {
                NODEROLE = "worker"
                RABBITMQUSER = "rabbit_production"
                RABBITMQPASS= "rab543tpasswrd"
            }
            when {
                // Only say hello if a "greeting" is requested
                expression { params.buildenvironment == 'Production' }
             }  
            steps { 
                input message: "Deploy to production?", ok: "Yes"
                checkout([$class: 'GitSCM', branches: [[name: '*/infrastructure']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'e93c7b8a-bfa5-4a31-a352-74df2827c304', url: 'https://bitbucket.org/AlexanderByndyu/orb.viridian.git']]])
                echo 'Deploy Rabbit to staging'
                sh "docker stack deploy --compose-file infrastructure/RabbitMQ/docker-compose.yml bsprd"
            }
        }
    }
}