# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # Install Docker Compose
  - apk add --update py-pip && pip install docker-compose

build-master:
  stage: build
  script:
    - docker-compose build
    - docker service rm bsapp_prometheus
    - docker config rm bsapp_task_rules
    - docker stack deploy --with-registry-auth --compose-file docker-compose.yml bsapp
   # - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master