name: publish
on:
  release:
    types: [published]
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: checkout
        uses: actions/checkout@master
           
      - name: install dotnet 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: install dotnet 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: build
        run: dotnet build
        
      - name: publish Byndyusoft.Dotnet.Core.Infrastructure.CQRS.Abstractions
        uses: alirezanet/publish-nuget@v3.0.2
        with:
          PROJECT_FILE_PATH: src/Infrastructure/CQRS.Abstractions/CQRS.Abstractions.csproj
          VERSION_FILE_PATH: src/Infrastructure/Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Dotnet.Core.Infrastructure.CQRS.Implementations
        uses: alirezanet/publish-nuget@v3.0.2
        with:
          PROJECT_FILE_PATH: src/Infrastructure/CQRS.Implementations/CQRS.Implementations.csproj
          VERSION_FILE_PATH: src/Infrastructure/Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true

      - name: publish Byndyusoft.Dotnet.Core.Infrastructure.Dapper
        uses: alirezanet/publish-nuget@v3.0.2
        with:
          PROJECT_FILE_PATH: src/Infrastructure/Dapper/Dapper.csproj
          VERSION_FILE_PATH: src/Infrastructure/Directory.Build.props
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
